### ISSUE TITLE
Crash occurs when talking to the fortune teller during the Stardew Valley Fair

### ISSUE THREAD

**Issue by andrewzah** [ThatNorthernMonkey/HarvestWithScythe#2]
log output:

```
[22:35:40 ERROR SMAPI] A mod failed handling the ControlEvents.MouseChanged event:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at HarvestWithScytheSMAPI.HarvestWithScytheSMAPI.HarvestCropsWithAScythe()
   at HarvestWithScytheSMAPI.HarvestWithScytheSMAPI.Events_MouseActionOnHoeDirt(Object sender, EventArgs e)
   at StardewModdingAPI.Framework.InternalExtensions.SafelyRaiseGenericEvent[TEventArgs](IMonitor monitor, String name, IEnumerable`1 handlers, Object sender, TEventArgs args) in D:\source\_Stardew\SMAPI\src\StardewModdingAPI\Framework\InternalExtensions.cs:line 57
[22:35:41 ERROR SMAPI] A mod failed handling the ControlEvents.MouseChanged event:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
```

**Comment by Valamyr** [comment]
Same issue. Worked fine on year 1, crash year 2
